### ISSUE TITLE
Nextflow summit

### ISSUE THREAD

**Issue by Midnighter** [quiltdata/nf-quilt3#2]
Unfortunately, I couldn't attend the nextflow summit in person so I didn't have the chance to talk to you in person. Once again, I was very excited about what quilt has to offer especially in combination with nextflow. I wasn't sure where to reach out. I'm happy to also chat by email, Slack, or have a video call. In the meantime, here are a bunch of questions that came to mind:

1. Is there a roadmap for supporting multiple AWS profiles, as well as MinIO (with several aliases)?
2. Will it be possible to create multiple packages from one pipeline run, for example, one package per sample?
3. Is it possible to create quilt packages that are essentially collections of other packages?
4. Is it possible to build a package in parts or extend an existing package and have the lineage information be tracked? As an example, say that I process a sample through three separate pipelines A, B, C. Say pipeline A creates a package `sample/1` which then serves as input to pipeline B. Rather than creating a new package, can pipeline B add its results to the package `sample/1`, with the whole package then forming the input to pipeline C that also adds its results? And will the lineage for the files in this package be correctly tracked?
5. I always imagine scenarios where I want to select all packages that were generated with an old version of a pipeline and submit them to be processed by the latest pipeline version. Probably fairly quick to code up with Python and NF Tower but maybe you already thought about it?

Thanks in advance!

**Comment by drernie** [comment]
Thanks. Replied directly.  Will follow-up in https://github.com/quiltdata/nf-quilt as appropriate.
